### ISSUE TITLE
Password is required to be added to the Gruntfile in plaintext

### ISSUE THREAD

**Issue by cmackley** [screeps/grunt-screeps#1]
This is a really nice addition to my Screeps workflow.  But I hate that I have to put my password directly into my Gruntfile.js.  If I want to put my code somewhere public, my screeps account can easily be compromised.  

Instead of two options for username and password, could there just be one that specifies a file that has these credentials?  Then the user could check in their Gruntfile but omit the credentials file.

**Comment by cmackley** [comment]
[Looks like it might be easy enough if the file is JSON](https://stackoverflow.com/questions/10011011/using-node-js-how-do-i-read-a-json-object-into-server-memory).  I might give it a try tonight.

**Comment by artch** [comment]
Grunt config is simply a node.js module. You can `require` any other modules (files) like that:

```javascript
var credentials = require('./credentials.js');

module.exports = function(grunt) {
    grunt.initConfig({
        screeps: {
            options: credentials,
            dist: {                
                src: ['dist/*.js']
            }       
        }
    });
}
```
**credentials.js**:
```javascript
module.exports = {
    email: 'EMAIL',
    password: 'PASSWORD',
    branch: 'default'
};
```
